name: smartagri
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  image_picker: ^1.0.5 # or the latest version
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  geolocator: ^14.0.0
  http: ^1.4.0
  provider: ^6.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/smart_agri_logo.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/smart_agri_logo.png"
