// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BdOcE0ktIFrVeFgXQr8zcp0m4Ll9TYA',
    appId: '1:491371167472:web:0225e07b28b375a44ccc35',
    messagingSenderId: '491371167472',
    projectId: 'mceresourcehub',
    authDomain: 'mceresourcehub.firebaseapp.com',
    storageBucket: 'mceresourcehub.firebasestorage.app',
    measurementId: 'G-PQ1QVV9E82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJyZH78LRzAK-AAWftKnQSzc5umwKDx0',
    appId: '1:491371167472:android:a03cdbf858f5beea4ccc35',
    messagingSenderId: '491371167472',
    projectId: 'mceresourcehub',
    storageBucket: 'mceresourcehub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGG_KqjK4ZvCOVkJve4B5py9MyxVCdV5o',
    appId: '1:491371167472:ios:2b4dabb9ec2129184ccc35',
    messagingSenderId: '491371167472',
    projectId: 'mceresourcehub',
    storageBucket: 'mceresourcehub.firebasestorage.app',
    iosBundleId: 'com.example.smartagriNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGG_KqjK4ZvCOVkJve4B5py9MyxVCdV5o',
    appId: '1:491371167472:ios:2b4dabb9ec2129184ccc35',
    messagingSenderId: '491371167472',
    projectId: 'mceresourcehub',
    storageBucket: 'mceresourcehub.firebasestorage.app',
    iosBundleId: 'com.example.smartagriNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9BdOcE0ktIFrVeFgXQr8zcp0m4Ll9TYA',
    appId: '1:491371167472:web:d6902ca5027bc26e4ccc35',
    messagingSenderId: '491371167472',
    projectId: 'mceresourcehub',
    authDomain: 'mceresourcehub.firebaseapp.com',
    storageBucket: 'mceresourcehub.firebasestorage.app',
    measurementId: 'G-0F07HTP3Q4',
  );

}